### ISSUE TITLE
html link in user manual for OBI specification is incorrect

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/cv32e40x#150]
### Description
The link in the user manual for the cv32e40x that points to the relevant OBI doc in core-v-docs is incorrect.

### Component
Indicate the component in which you found a problem (and we will add the appropriate label):

**Component:Doc **: For issues in the Documentation (e.g. for User Manual or README.md files)

### Steps to Reproduce
Try the OPENHW-OBI link in this section of the user manul

https://cv32e40x-user-manual.readthedocs.io/en/latest/intro.html

**Comment by Silabs-ArjanB** [comment]
Fixed with https://github.com/openhwgroup/cv32e40x/pull/152
