### ISSUE TITLE
PMA does not implement misaligned checks

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40x#185]
Following should be added to the PMA:

  input logic        misaligned_access_i,

Misaligned accesses to I/O should be forbidden.
On the instruction side: If attempting to execute from I/O and the access is misaligned as well, then the error related to the failed execute attempt has highest priority (so exception code 1).

**Comment by silabs-oysteink** [comment]
This issue was fixed with PR #193
