### ISSUE TITLE
RVFI may set dpc before entering debug handler during single-step mode

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/cv32e40x#187]
### Component
**Component:RVFI**
**Component:Doc **: For issues in the Documentation (e.g. for User Manual or README.md files)
**Component:Other**: For any other issues

### Steps to Reproduce
Please provide:
1. e422fa37d0f5c50e526dbfddb01f927c7d1fd513 (cv32e40x/dev branch)
2. Using Xcelium 21.07.a001
```
%  makeuvmt test TEST=debug_test WAVES=1 ADV_DEBUG=1 SEED=1680260209 CV_CORE=cv32e40x
```

The RVFI will report the dpc CSR updating to the "next" instruction during the instruciton retirement of the stepped instruction (0xca94).  However the ISS will always wait until the first instruction retirement in the debug handler before updating dpc to the next instruction (0xca98).  This behavior is intermittent-not all single-stepped instructions show this behavior on RVFI.

![image](https://user-images.githubusercontent.com/56401023/129760575-d853d940-0033-4c9e-94f2-5b1e977b2b4a.png)

**Comment by silabs-halfdan** [comment]
@silabs-oysteink will implement a fix for this in RTL.

**Comment by Silabs-ArjanB** [comment]
Hi @silabs-oysteink , this also touches on the discussion we just had. Here you could also argue that all instructions should set dpc as part of their execution in single step mode.

**Comment by silabs-oysteink** [comment]
Agreed @Silabs-ArjanB, there will be a PR shortly which fixes this and also aligns on CSR update when the stepped instruction retires.

**Comment by Silabs-ArjanB** [comment]
Should be fixed with https://github.com/openhwgroup/cv32e40x/pull/192

**Comment by strichmo** [comment]
Confirmed fixed.  The debug_test is passing robustly with and without random stalls.
