### ISSUE TITLE
non-naturally aligned half-word load/store to PMA I/O regions do not trigger PMA access faults

### ISSUE THREAD

**Issue by silabs-hfegran** [openhwgroup/cv32e40x#206]
### PMA/LSU
Half-word accesses with address bit[1:0] = 01 to PMA I/O regions (including memory not covered by any PMA-region, i.e. I/O by default) does not trigger an access fault, as this is not considered misaligned by the LSU.
Only misaligned half-words that triggers another load/store operation is flagged as misaligned (i.e. bit[1:0] = 11 for halfword accesses).

**Comment by Silabs-ArjanB** [comment]
Should be fixed with https://github.com/openhwgroup/cv32e40x/pull/230

**Comment by silabs-hfegran** [comment]
Thanks for the Fix @silabs-oysteink , passes previously failing tests now
