### ISSUE TITLE
Removing extension interface section from Documentation and link to the official one

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/cv32e40x#236]
The cv32e40x documentation regarding the core-v-x interface should only contain references to the official spec: https://docs.openhwgroup.org/projects/openhw-group-core-v-xif/ .

In addition, it may specify what is supported and what not, which signals are hardwired, etc which are related to implementation details

**Comment by Silabs-ArjanB** [comment]
Hi @davideschiavone, can this be closed now (we accept the extra effort of keeping two documents in sync)?

**Comment by davideschiavone** [comment]
correct
