### ISSUE TITLE
XIF - Implement commit/kill for offloaded instructions in controller FSM

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40x#275]
This task relates to finishing one of the known open items from https://github.com/openhwgroup/cv32e40x/pull/272:

- The controller commits all offloaded instructions regardless of any exceptions.

Decide on commit/kill boundary in the controller. E.g. will we again differentiate between load/store and other instructions, can offloaded load/stores still be killed before or at same time as they use their memory request/response interface?

**Comment by silabs-oysteink** [comment]
Implemented with PR #326
