### ISSUE TITLE
core locks up with interrupt pending

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/cv32e40x#317]
### Component

**Component:RTL**

### Steps to Reproduce
Please provide:
1. USe cv32e40x/dev branch of main core-v-verif repo: 2c6e09f6b255692bc4e81812af1cb80ece36d60e
2. makeuvmt clean comp_corev-dv gen_corev-dv test TEST=corev_rand_interrupt_wfi SEED=-1071415937 WAVES=1 ADV_DEBUG=1 CFG=pma_test_cfg_3

The core executes for a while then simply stops after a store:
```
  216233.000 ns | RVFI |    61847 |   4418 | 0000a740 | 03d09b03 | M | x1  | 6400c973 | x0  | 00000000 | x22 | 00000000 |  RD | 6400c9b0 | ----0000 | sub_6_2_0_t corev_rand_interrupt_wfi_0.S 440 - lh x22,61(x1)
  216245.000 ns | RVFI |    61848 |   4419 | 0000a744 | 300465f3 | M | x0  | 00000000 | x0  | 00000000 | x11 | 00001880 |  -- | -------- | -------- | sub_6_2_0_t corev_rand_interrupt_wfi_0.S 441 - csrrsi x11,mstatus,8
  216260.000 ns | RVFI |    61851 |   4420 | 0000a748 | f3408da3 | M | x1  | 6400c973 | x20 | 00000000 | x0  | 00000000 |  WR | 6400c8ae | ------00 | sub_6_2_0_t corev_rand_interrupt_wfi_0.S 442 - sb x20,-197(x1)
```

The core appears to believe an interrupt is pending, but does not proceed.

**Comment by Silabs-ArjanB** [comment]
Hi @strichmo This should be fixed now; could you re-run on this commit please and close this issue if it looks okay?
