### ISSUE TITLE
rvfi_trap not correct for single step instructions

### ISSUE THREAD

**Issue by silabs-oysteink** [openhwgroup/cv32e40x#342]
## Bug Title
rvfi_trap not correct for single step instructions

### Component
**Component:RTL**: RVFI

### Steps to Reproduce
The steps provided in issue #340 can be used for this issue as well. Any single stepped instruction in the test seems to exhibit this behavior:

The single step instruction reaches WB and generates a wb_valid, which leads to rvfi_valid with no bits set in rvfi_trap. rvfi_trap_next can be seen to have some bits set at the same time as rvfi_valid is high (marked in blue in the figure), but these does not seem to correspond to the user manual description of rvfi_trap.

<img width="558" alt="rvfi_trap" src="https://user-images.githubusercontent.com/66771756/144853860-c1d15aba-2cb2-47df-be4d-01d759cfc9bb.png">
.

**Comment by silabs-halfdan** [comment]
RVFI uses the pc_mux to detect synchronous debug entries. As the single step debug entry updates the mux the cycle after wb_valid, it will need to be triggered separately and can not use the exception code signal from ctrl_fsm_o.
![image](https://user-images.githubusercontent.com/78801928/147570920-d7f75db6-3191-4719-90db-7fa786062649.png)
.

**Comment by Silabs-ArjanB** [comment]
@silabs-oysteink Can this one be closed now?

**Comment by silabs-oysteink** [comment]
Yes, closing it.
