### ISSUE TITLE
tinfo and tcontrol CSRs should be MRW

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40x#399]
The tinfo and tcontrol CSRs are wrongly listed as MRO in https://cv32e40x-user-manual.readthedocs.io/en/latest/control_status_registers.html#csr-map. They should be MRW. Please check whether the RTL is correct as well.

**Comment by Silabs-ArjanB** [comment]
Documentation has already been fixed. Just need to check the RTL.

**Comment by silabs-oysteink** [comment]
RTL looks good. Writes are ignored for both CSRs, and reads return 0 for tcontrol and the supported trigger type(s) for tinfo.
