### ISSUE TITLE
Issue illegal instruction for deconfigured B extensions

### ISSUE THREAD

**Issue by silabs-oivind** [openhwgroup/cv32e40x#402]
Illegal instruction won't be issued from the B decoder if trying to execute a deconfigured instruction.

In the example below (and other similar ones), add "else  decoder_ctrl_o = DECODER_CTRL_ILLEGAL_INSN":

         {7'b001_0000, 3'b010}: begin // Shift left by 1 and add (sh1add)
            if (RV32B_ZBA) begin
              decoder_ctrl_o.alu_operator = ALU_B_SH1ADD;
            end
          end

**Comment by Silabs-ArjanB** [comment]
Also put the carryless multiplication circuit in the ALU in a generate statement as it it not obvious that it will get optimized away if not used.

**Comment by Silabs-ArjanB** [comment]
@silabs-oivind  Please close this issue if you agree it has been solved.
