### ISSUE TITLE
Transition from debug_havereset to debug_halted not possible

### ISSUE THREAD

**Issue by silabs-oysteink** [openhwgroup/cv32e40x#410]
The debug state fsm currently does not allow the transition from debug_havereset to debug_halted (see image).
![image](https://user-images.githubusercontent.com/66771756/151547288-cddb8b95-6b9e-4f8d-8f73-ab7a85e401d9.png)

The controller needs an update to ensure the transition will be possible. If debug_req_i is asserted early, the core will set debug_havereset -> debug_running -> debug_halted. Possible solution is to check for debug entry in the state BOOT_SET, and se debug_mode_n accordingly.

**Comment by Silabs-ArjanB** [comment]
Fixed by https://github.com/openhwgroup/cv32e40x/pull/747
