### ISSUE TITLE
Update RTL according to User Manual - mtvec, mcause, etc.

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40x#434]
The following need to be updated in the RTL to match the User Manual:

- mtvec: Make aligned to 128 bytes
- mtvec: Update initial value according to new dependency on mtvec_addr_i
- mtvec: Make MODE a 2-bit WARL field with 0x0 as resolution value (SMCLIC = 0)
- mtvec: Make MODE a 2-bit WARL field with 0x3 as resolution value (SMCLIC = 1)
- mtvt: Make aligned to 2^(2+SMCLIC_ID_WIDTH) bytes
- mcause: Make exccode a 11-bit field
- tselect: Make WARL field with (DBG_NUM_TRIGGERS-1) as the value used when writing an illegal value.
- tdata1.type: Make WARL field with 0x6 as resolution value.
- mcontrol6.match: Make WARL field with 0x0 as resolution value
- Update NMI exception codes (store bus fault NMI (1025), load bus fault NMI (1024)
- (CV32E40S only) Update NMI exception codes (store parity/checksum fault NMI (1027), load parity/checksum fault NMI (1026)
- (CV32E40S only) Make mstatus.MPP a WARL field with 0x0 as resolution value

Note that the mtvec/mcause related changes require changes in if_stage, top level, etc. as well (check where these signals are used)

**Comment by Silabs-ArjanB** [comment]
Update rvfi_intr[10:3] in docs/user_manual/source/rvfi.rst and RVFI itself

**Comment by silabs-oysteink** [comment]
All bullets above should already be implemented as requested, with the following exceptions due to spec changes since the issue was created:

- mtvec.mode is WARL(0,1) instead of WARL(0*, 1) in CLINT mode (in line with user manual)
- tselect is WARL(0-DBG_NUM_TRIGGERS-1), not resolving to (DBG_NUM_TRIGGERS-1) but keeping old value
- tdata1.type is now WARL(2,5,6,15*)

**Comment by xiaoweish** [comment]
Hi @Silabs-ArjanB 
Could you share the reasoning behind `mtvec: Make aligned to 128 bytes`

Of course, it's legal according to [CLIC spec](https://github.com/riscv/riscv-fast-interrupt/blob/master/src/clic.adoc#384-new-mtvec-csr-mode-for-clic) :


> 3.8.4. New mtvec CSR Mode for CLIC
> The CLIC interrupt-handling mode is encoded as a new state in the existing mtvec WARL register, where mtvec.mode (the two least-significant bits) is 11, and bits mtvec[5:2] (mtvec.submode) are zero. The other encodings of mtvec.submode are reserved for future use. The trap vector base address is specified as the upper XLEN-6 bits of mtvec (base) with six lower zero bits appended, which constrains **alignment on a 64-byte or larger power-of-two boundary**.

**Comment by Silabs-ArjanB** [comment]
Hi @xiaoweish , that is primarily done to speed up the fetch stage (PC computation) when CLINT vectored mode is being used. For CLIC we want the mtvec alignment simply be the same as for CLINT. The design started from the CV32E40P where the alignment requirement was 256 bytes. We improved upon that as much as we could honoring both CLIC and CLINT constraints (and fetch stage speed requirements).

**Comment by xiaoweish** [comment]
Thanks @Silabs-ArjanB for your clear explanations!
