### ISSUE TITLE
Remove (need for) USE_DEPRECATED_FEATURE_SET

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40x#472]
Remove need for USE_DEPRECATED_FEATURE_SET

If USE_DEPRECATED_FEATURE_SET = 1, then: Use deprecated ``nmi_addr_i`` input and use 8 instead of 11 bits for the **EXCCODE** in ``mcause``.                               

Can be removed when relative nmi address(MTVEC + 15*4) and 11 bit exception code is supported in core-v-verif.

**Comment by Silabs-ArjanB** [comment]
Exception codes values depend on the USE_DEPRECATED_FEATURE_SET setting as well.

**Comment by silabs-oysteink** [comment]
This issue should now be fixed.
