### ISSUE TITLE
Implement prot[0] bit correctly for pointer fetches and assert no back-to-back data fetches on OBI

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40x#500]
https://github.com/openhwgroup/cv32e40x/pull/492 has the following open feedback that needs to be addressed related to if_stage:

- prot[0] assignment needs to be updated.
- Add assertion that no back-to-back data (pointer) fetches can occur on instruction OBI.

**Comment by silabs-oysteink** [comment]
I believe the prot[0] is already in place, 1 for CLIC pointer fetches and 0 otherwise. Assertion is still pending.

**Comment by Silabs-ArjanB** [comment]
True
