### ISSUE TITLE
Add asesrtion that pending CLIC nmi cannot be missed

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40x#502]
The pending CLIC NMI signal (pending_clic_nmi) will only be high for 1 cycle. Assert that if it is high, then the FSM is in its FUNCTIONAL state, pending_nmi =1, and nmi_allowed = 1.

Also explain if it can occur in debug mode or during single stepping.

Explain why pending_nmi_early did not need to be updated.

**Comment by Silabs-ArjanB** [comment]
Can an additional assertion be added that no wb_valid = 1 can only occur in some FSM states (FUNCTIONAL, ... (need to better define this)

**Comment by silabs-oysteink** [comment]
Since CLIC fetches are now all instructions fetches this issue is no longer relevant.
