### ISSUE TITLE
Analyze branch bypass removal

### ISSUE THREAD

**Issue by silabs-halfdan** [openhwgroup/cv32e40x#52]
Analyze effects of removing branch bypass and whether it affects design choices for the new controller.

The commit with bypass removed:
https://github.com/openhwgroup/cv32e40x/pull/51/commits/94c89ff77c13c291f7939082f5c6bd6138a45ac7

**Comment by Silabs-ArjanB** [comment]
See https://github.com/openhwgroup/cv32e40x/pull/51

**Comment by silabs-oysteink** [comment]
The change here was that 'branch_in_ex' was removed from 'ex_ready_o'.
For the E40P, this allowed branches to retire from the EX stage without having to propagate to the WB stage. This could potentially lead to a small performance gain as instructions after the branch were allowed to enter EX even though the WB stage was not  yet ready.

For the E40X and E40S, we have a new controller, and all instructions retire from the WB stage. This makes it impossible to retire branches from EX as above, and thus this change would have been needed when the new controller was introduced anyway.
![image](https://user-images.githubusercontent.com/66771756/150542646-632535d5-6e1f-434a-8c2c-f94f02d3aa05.png)
