### ISSUE TITLE
mcause reset value 0x0000_0000 with SMCLIC=1 violates CLIC spec

### ISSUE THREAD

**Issue by silabs-hfegran** [openhwgroup/cv32e40x#549]
## mcause reset value 0x0000_0000 with SMCLIC=1 violates CLIC spec

> 5.7. Changes to xcause CSRs 
(...) The mcause.mpp and mcause.mpie fields mirror the mstatus.mpp and mstatus.mpie fields, and are aliased into mcause to reduce context save/restore code.

mcause
![image](https://user-images.githubusercontent.com/75469886/169749559-d82ceced-75bc-4bd2-822d-c1f98286d9ed.png)

mstatus
![image](https://user-images.githubusercontent.com/75469886/169749743-a553b29f-a36f-46e0-87af-202c27549937.png)

Currently mcause resets to 0x0000_0000 with SMCLIC parameter = 1, this causes a mismatch between the hard-coded 2'b11 value of mstatus.mpp and mcause.mpp after reset. Furthermore, 2'b00 is not a supported value with the WARL-scheme for this register. 

### Component
**Component:RTL**: CSR behavior after reset
**Component:Doc**: User manual CSR description

### Steps to Reproduce
Currently only on internal development branch, problem is present as soon as CLIC is enabled in RTL and ISS.

**Comment by Silabs-ArjanB** [comment]
Hi @silabs-hfegran I think (by luck) the RTL is actually correct, but it is quite confusing and not written in our regular way, which likely caused it to be hooked up wrongly to RVFI (which I guess is what you then observed). I will clean up the RTL and what values RVFI gets to see.

**Comment by silabs-hfegran** [comment]
Great, thanks for looking into this @Silabs-ArjanB

**Comment by Silabs-ArjanB** [comment]
@silabs-hfegran This should be fixed now.
