### ISSUE TITLE
mscratchcswl and mscratchcsw should operate on mscratch

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40x#589]
mscratchcswl and mscratchcsw  are currently implemented as regular CSRs and not according to the pseudo code stated in the CLIC specification.

Take https://github.com/riscv/riscv-fast-interrupt/pull/241 into account as well.

**Comment by Silabs-ArjanB** [comment]
@silabs-oysteink Has this been fixed now including the mentioned issue 241?

**Comment by silabs-oysteink** [comment]
Code is actually using mcause.mpp, so we are not compliant with the issue mentioned.

**Comment by Silabs-ArjanB** [comment]
@silabs-oysteink Should be a SEC clean change to get it fixed then; I will add it in the coming sprint.

**Comment by silabs-oysteink** [comment]
This issue should now be fixed.
