### ISSUE TITLE
E40X 0.3.0 : Doc, Updated WARL behavior of pmpxcfg by @Silabs-ArjanB in #491

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/cv32e40x#600]
In the Documentation Changes from 0.2.0 to 0.3.0, it says

> Updated WARL behavior of pmpxcfg by @Silabs-ArjanB in #491

I cannot find any differences in the pdf documentation between 0.2.0 and 0.3.0 referring to pmp, could you please identify the difference in the text.

**Comment by Silabs-ArjanB** [comment]
Hi @eroom1966 , please see the mentioned pull request: https://github.com/openhwgroup/cv32e40x/pull/491/files

**Comment by Silabs-ArjanB** [comment]
@Imperas The changelist is autogenerated and can therefore contain comments that do not actually apply to the specific core itself. Such non-applicable content does not impact (and is not visible in) the actual content (i.e. everything else than the autogenerated change list) of the pdf . If you would simply do a 'pdf diff' on two released versions of the user manual and ignore diffs in the change list itself, you will have an accurate overview of the changes. 

There is not need for Imperas to look in the documentation source files or in the RTL files. Please let me know if this works for you. If not, then we will filter the change list going forward to exclude potentially misleading content.

We can agree to increment the 'patch' part of the version number for incremental changes that don't change the spec, but in reality that will not help you much as user manual releases are infrequent and bundle multiple changes (so the chance of there only being 'patch' releases in such bundle is very low).

**Comment by Silabs-ArjanB** [comment]
@eroom1966 Can this ticket be closed now?
