### ISSUE TITLE
Mirroring of mstatus.mpp wrong when writing mcause

### ISSUE THREAD

**Issue by silabs-oivind** [openhwgroup/cv32e40x#640]
Upon mcause_we, the the value written to mstatus.mpp is taken from wrong bit indices (from cv32e40x_cs_registers):
`mstatus_n.mpp  = mstatus_mpp_resolve(mstatus_rdata.mpp, csr_wdata_int[MSTATUS_MPP_BIT_HIGH:MSTATUS_MPP_BIT_LOW]);`

Indices from mcause (not mstatus) should be used.

For e40x mstatus_mpp_resolve() will always return PRIV_LVL_M, so it will not result in a real issue. Code should be cleaned up though.

**Comment by Silabs-ArjanB** [comment]
@silabs-oivind  Please close this issue if you agree it has been solved.
