### ISSUE TITLE
User Manual: Update the mtval description

### ISSUE THREAD

**Issue by silabs-robin** [openhwgroup/cv32e40x#65]
The user manual describes `mtval` as being RO hard-wired to zero.
https://cv32e40x-user-manual.readthedocs.io/en/latest/control_status_registers.html#machine-trap-value-mtval
This should be updated to match 40X/S plans.

**Comment by silabs-robin** [comment]
@Silabs-ArjanB

**Comment by Silabs-ArjanB** [comment]
Thanks @silabs-robin , we have not fully decided yet on whether we will actually implement this (which is indeed our original plan) or not. Will keep this ticket open until that decision has been made.

**Comment by Silabs-ArjanB** [comment]
@silabs-robin We decided to stick to mtval = 0x0

**Comment by silabs-robin** [comment]
Alright. I see the spec reflects this as well.
