### ISSUE TITLE
Race between disable_iff and assertion

### ISSUE THREAD

**Issue by dawidzim** [openhwgroup/cv32e40x#67]
Hey!
I think there is a possible race between disable_iff and assertion. CLK signal which triggering assertion is set earlier than RST, so assertion will be executed and fail. Maybe good idea is change `disable iff (!rst_n)` to `disable iff (rst_n != 1)`  in this way we will disable assertion when `rst_n = x`

LRM 1800-2017 chapter 16.12:
```
If the disable condition is true at anytime between the
        start of the attempt in the Observed region, inclusive, and
        the end of the evaluation attempt, inclusive, then the overall
        evaluation of the property results in disabled.
```

**Comment by silabs-oysteink** [comment]
Setting this as wont-fix. We are not able to reproduce the suggested issue above.
