### ISSUE TITLE
Change 'parameter int' into 'parameter int unsigned'

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40x#676]
This is to match the CORE-V-XIF specification. Also all other use of 'parameter int' does not make sense and should be changed into 'parameter int unsigned'.

This applies to the entire repos bhv, rtl, doc, etc. (and to surrounding modules instantiating this core)

**Comment by Silabs-ArjanB** [comment]
Hi @silabs-oivind Can this issue be closed now?

**Comment by silabs-oivind** [comment]
> Member

Yes.
