### ISSUE TITLE
mnxti reads return incorrect value when CLIC_ID_WIDTH = 1

### ISSUE THREAD

**Issue by silabs-mateilga** [openhwgroup/cv32e40x#884]
**Component:RTL**

Reads of csr mnxti, that should return the value of csr mtvt + XLEN/8 * clic_id, does not return correct value when the id width is 1. Debugging with @silabs-oysteink indicates that this applies for all widths < 4. 

Reproduce by formally proving `...core_i.clic_assert_i.gen_clic_assertions.a_mnxti_case_1_irq_req_unchanged` 
with branch: `https://github.com/silabs-mateilga/core-v-verif/tree/clic_assert_mtvt_fields`
on the cv32e40s core

**Comment by silabs-mateilga** [comment]
The fix to core-v-verif is now merged, reproduction can be accomplished in the `cv32e40s/dev`-branch of core-v-verif.

**Comment by silabs-oysteink** [comment]
Fixed with PR #478 (merge from CV32E40X)

**Comment by silabs-mateilga** [comment]
Fix verified in formal
