### ISSUE TITLE
CV32E40X should not use misaligned exceptions

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40x#975]
The Load address misaligned and Store/AMO address misaligned exceptions should be replaced by access faults instead. Reason is that misaligned exceptions imply that emulation is possible, but that would in turn require that regular loads/stores with the same address / access type would cause misaligned exceptions as well (which they don't).

**Comment by Silabs-ArjanB** [comment]
Hi @silabs-oysteink Can this be closed now?

**Comment by silabs-oysteink** [comment]
> Hi @silabs-oysteink Can this be closed now?

Yes.
