### ISSUE TITLE
FPGA problem synthesis

### ISSUE THREAD

**Issue by SoCScholar** [openhwgroup/cv32e40x#985]
Hi,

I encountered some issues while running the **synthesis** and **implementation** in Vivado. Despite carefully following the provided instructions, the process did not work as expected.  Can you please let me know where i missed.  

https://docs.openhwgroup.org/projects/cv32e40x-user-manual/en/latest/intro.html#synthesis-guidelines

Thank you so much. 

with Best regards  
 
Here is screenshot in vivado

![image](https://github.com/user-attachments/assets/6d9cec73-a889-42ea-96f2-7ae720611cd5)

![Screenshot from 2024-10-11 14-47-33](https://github.com/user-attachments/assets/41c2d605-2a02-43e8-8b42-3cf57f81def2)

**Comment by Silabs-ArjanB** [comment]
Hi,

It seems you missed this guidelines and tried to synthesize a higher level behavioral module:

![image](https://github.com/user-attachments/assets/1ff60d36-0abc-4d8b-abe4-828d66b9081e)

**Comment by Silabs-ArjanB** [comment]
The wrapper is for simulation purposes only (it includes for example assertions). It is in the _bhv_ (behavioral) directory and files in that directory are not meant for synthesis. Only files inside the _rtl_ directory are meant for synthesis.
