### ISSUE TITLE
Which FPGA ?

### ISSUE THREAD

**Issue by SoCScholar** [openhwgroup/cv32e40x#986]
Hi,

Which **FPGA** do you suggest for running CV 32 E 40 X ? While compiling with genesys 2 (XC7K325T-2FFG900C), it says area over utilization.  The design contain 724 I/0 Ports but my fpga only has 500 Usable I/O Port. 

After running implementation

![Screenshot from 2024-10-11 16-20-37](https://github.com/user-attachments/assets/22120e0c-a66d-4c63-b28b-415c65162fd3)

After  running synthesis

![Screenshot from 2024-10-11 16-26-17](https://github.com/user-attachments/assets/bf040081-1c13-402d-99bd-94d1fc352969)

**Comment by Silabs-ArjanB** [comment]
We have no FPGA recommendations. You could reduce the pressure on FPGA port usage by connecting many of the CV32E40X ports to buses, memories, etc. that you model inside the FPGA (instead of outside). You would have to provide such system level components yourself.
